export const COMMISSION_RATE = 0.20;
export const MAX_BOOKINGS_PER_DAY = 10;
export const OTP_EXPIRY_SECONDS = 300;
export const JWT_EXPIRY = '7d';
export const JWT_REFRESH_EXPIRY = '30d';
export const SUPPORTED_LANGUAGES = ['en', 'hi', 'bn'] as const;
export const DEFAULT_LANGUAGE = 'en';
export const CURRENCY = 'INR';
export const CURRENCY_SYMBOL = '₹';
export const MAX_FILE_SIZE_MB = 50;
export const ALLOWED_FILE_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'video/mp4', 'video/quicktime'];
export const PAGINATION_DEFAULT_LIMIT = 20;
export const PAGINATION_MAX_LIMIT = 100;
export const SEARCH_RADIUS_KM = 50;
export const REVIEW_MIN_LENGTH = 10;
export const REVIEW_MAX_LENGTH = 1000;
export const RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;
export const RATE_LIMIT_MAX_REQUESTS = 100;

export const DEITIES = [
  { id: 'shiva', name: 'Shiva', nameHi: 'शिव', nameBn: 'শিব', icon: '🕉️', color: '#E8F5E9' },
  { id: 'krishna', name: 'Krishna', nameHi: 'कृष्ण', nameBn: 'কৃষ্ণ', icon: '🪈', color: '#E3F2FD' },
  { id: 'durga', name: 'Durga', nameHi: 'दुर्गा', nameBn: 'দুর্গা', icon: '🦁', color: '#FCE4EC' },
  { id: 'hanuman', name: 'Hanuman', nameHi: 'हनुमान', nameBn: 'হনুমান', icon: '🙏', color: '#FFF3E0' },
  { id: 'lakshmi', name: 'Lakshmi', nameHi: 'लक्ष्मी', nameBn: 'লক্ষ্মী', icon: '🌺', color: '#F3E5F5' },
  { id: 'kali', name: 'Kali', nameHi: 'काली', nameBn: 'কালী', icon: '🔱', color: '#EDE7F6' },
  { id: 'ram', name: 'Ram', nameHi: 'राम', nameBn: 'রাম', icon: '🏹', color: '#E8EAF6' },
  { id: 'ganesh', name: 'Ganesh', nameHi: 'गणेश', nameBn: 'গণেশ', icon: '🐘', color: '#FFF8E1' },
  { id: 'saraswati', name: 'Saraswati', nameHi: 'सरस्वती', nameBn: 'সরস্বতী', icon: '📚', color: '#E0F7FA' },
  { id: 'vishnu', name: 'Vishnu', nameHi: 'विष्णु', nameBn: 'বিষ্ণু', icon: '🌀', color: '#E0F2F1' },
] as const;

export const FESTIVALS_2026 = [
  { name: 'Maha Shivratri', date: '2026-02-26', deity: 'shiva' },
  { name: 'Holi', date: '2026-03-10', deity: 'krishna' },
  { name: 'Navratri', date: '2026-10-12', deity: 'durga' },
  { name: 'Diwali', date: '2026-11-08', deity: 'lakshmi' },
  { name: 'Janmashtami', date: '2026-08-14', deity: 'krishna' },
  { name: 'Ganesh Chaturthi', date: '2026-09-05', deity: 'ganesh' },
  { name: 'Raksha Bandhan', date: '2026-08-29', deity: 'vishnu' },
  { name: 'Dussehra', date: '2026-10-21', deity: 'durga' },
] as const;

export const PUJA_CATEGORIES = [
  { id: 'puja', name: 'Puja', icon: '📿' },
  { id: 'hawan', name: 'Hawan', icon: '🔥' },
  { id: 'aarti', name: 'Aarti', icon: '🕯️' },
  { id: 'sanskar', name: 'Sanskar', icon: '👶' },
  { id: 'tarpan', name: 'Tarpan', icon: '💧' },
  { id: 'daily', name: 'Daily', icon: '☀️' },
  { id: 'festival', name: 'Festival', icon: '🏮' },
] as const;

export const RITUALS = [
  {
    id: 'satyanarayan',
    name: 'Satyanarayan Puja',
    nameHi: 'सत्यनारायण पूजा',
    slug: 'satyanarayan-puja',
    description: 'A sacred ritual performed to worship Lord Satyanarayan, an avatar of Lord Vishnu, to bring peace, prosperity, and happiness to the home.',
    shortDescription: 'Sacred ritual for Lord Vishnu bringing peace and prosperity.',
    category: 'puja' as const,
    type: 'both' as const,
    deityId: 'vishnu',
    associatedDeities: ['vishnu', 'lakshmi'],
    image: 'https://images.unsplash.com/photo-1545128485-c400e7702796',
    icon: '📿',
    pricing: { basic: 1100, standard: 2100, premium: 5100 },
    duration: { basic: 45, standard: 75, premium: 120 },
    includes: ['Mantra Chanting', 'Prasad Blessing', 'Devotional Aarti'],
    requirements: ['Fresh fruits', 'Flowers', 'Paan leaves', 'Sweets'],
    samagri: ['Roli', 'Chawal', 'Kalash', 'Satyanarayan Katha Book', 'Desi Ghee'],
    benefits: ['Brings wealth and prosperity', 'Resolves domestic issues', 'Ensures family well-being'],
    isPopular: true,
    isTrending: true,
    isActive: true,
    order: 1,
  },
  {
    id: 'rudrabhishek',
    name: 'Rudrabhishek Hawan',
    nameHi: 'रुद्राभिषेक हवन',
    slug: 'rudrabhishek-hawan',
    description: 'An extremely powerful and ancient Vedic ritual performed to invoke the blessings of Lord Shiva in his Rudra form. It cleanses sins and removes all worldly obstacles.',
    shortDescription: 'Powerful Vedic ritual to invoke the blessings of Lord Shiva.',
    category: 'hawan' as const,
    type: 'both' as const,
    deityId: 'shiva',
    associatedDeities: ['shiva'],
    image: 'https://images.unsplash.com/photo-1608976477549-30113dc8d0e7',
    icon: '🔱',
    pricing: { basic: 1500, standard: 3100, premium: 7500 },
    duration: { basic: 60, standard: 90, premium: 150 },
    includes: ['Panchamrut Abhishek', '108 Shiva Chants', 'Rudra Path recitations'],
    requirements: ['Milk', 'Curd', 'Honey', 'Belpatra', 'Bhaang'],
    samagri: ['Gangajal', 'Rudraksha mala', 'Camphor', 'Hawan wood', 'Janeu'],
    benefits: ['Removes negative planetary energy', 'Brings absolute health and longevity', 'Eliminates fears'],
    isPopular: true,
    isTrending: true,
    isActive: true,
    order: 2,
  },
  {
    id: 'lakshmi_puja',
    name: 'Lakshmi Puja',
    nameHi: 'लक्ष्मी पूजा',
    slug: 'lakshmi-puja',
    description: 'A beautiful devotional puja to invoke Goddess Lakshmi for wealth, monetary success, positive vibrations, and removal of financial obstacles.',
    shortDescription: 'Devotional puja to Goddess Lakshmi for financial growth.',
    category: 'puja' as const,
    type: 'both' as const,
    deityId: 'lakshmi',
    associatedDeities: ['lakshmi', 'ganesh'],
    image: 'https://images.unsplash.com/photo-1561571994-3c61c554181a',
    icon: '🌺',
    pricing: { basic: 1100, standard: 2500, premium: 5500 },
    duration: { basic: 45, standard: 60, premium: 90 },
    includes: ['Lakshmi Ashtottara recitations', 'Ganesh Puja invocation', 'Aarti & Pushpanjali'],
    requirements: ['Lotus flowers', 'Red cloth', 'Dry fruits', 'Silver coin'],
    samagri: ['Kumkum', 'Haldi', 'Attar', 'Coconuts', 'Saffron'],
    benefits: ['Attracts legal wealth', 'Stabilizes commercial businesses', 'Fosters harmony'],
    isPopular: true,
    isTrending: false,
    isActive: true,
    order: 3,
  },
  {
    id: 'navgraha_puja',
    name: 'Navgraha Shanti Puja',
    nameHi: 'नवग्रह शांति पूजा',
    slug: 'navgraha-shanti-puja',
    description: 'A targeted ritual performed to pacify and gain the benevolent blessings of the nine planetary deities (Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, and Ketu).',
    shortDescription: 'Planetary pacification ritual for success and health.',
    category: 'puja' as const,
    type: 'both' as const,
    deityId: 'shiva',
    associatedDeities: ['shiva', 'ganesh'],
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf',
    icon: '🌍',
    pricing: { basic: 2100, standard: 4100, premium: 8100 },
    duration: { basic: 90, standard: 120, premium: 180 },
    includes: ['Nine Graha Mantras', 'Special Homa / Hawan', 'Prasad shipment'],
    requirements: ['Nine colored clothes', 'Navadhanya seeds', 'Sesame oil'],
    samagri: ['Navgraha wood sticks', 'Navgraha yantra', 'Black sesame'],
    benefits: ['Reduces professional setbacks', 'Minimizes health issues', 'Removes doshas'],
    isPopular: false,
    isTrending: true,
    isActive: true,
    order: 4,
  },
  {
    id: 'grihapravesh',
    name: 'Griha Pravesh Puja',
    nameHi: 'गृह प्रवेश पूजा',
    slug: 'griha-pravesh-puja',
    description: 'A crucial housewarming ceremony performed before moving into a new home to purify the surroundings from negative energy and invite divine fortune.',
    shortDescription: 'Purifying housewarming ritual for a new household.',
    category: 'sanskar' as const,
    type: 'home' as const,
    deityId: 'ganesh',
    associatedDeities: ['ganesh', 'lakshmi', 'vishnu'],
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f',
    icon: '🏡',
    pricing: { basic: 3100, standard: 5100, premium: 11000 },
    duration: { basic: 90, standard: 150, premium: 240 },
    includes: ['Vastu Shanti Puja', 'Ganesh Hawan', 'Kalash Pravesh walk'],
    requirements: ['Milk for boiling', 'Mango leaves', 'Fresh garlands'],
    samagri: ['Vastu Yantra', 'Hawan samagri', 'Camphor', 'Pancha Dhatu'],
    benefits: ['Sanctifies the house', 'Invites prosperity and happiness', 'Assures peaceful dwelling'],
    isPopular: true,
    isTrending: false,
    isActive: true,
    order: 5,
  },
  {
    id: 'pitrutarpan',
    name: 'Pitru Tarpan',
    nameHi: 'पितृ तर्पण',
    slug: 'pitru-tarpan',
    description: 'A highly sacred ancestral ritual performed to offer water and sesame seeds to the departed souls of ancestors, ensuring their spiritual peace and liberation.',
    shortDescription: 'Sacred water offering ritual for ancestral peace.',
    category: 'tarpan' as const,
    type: 'both' as const,
    deityId: 'shiva',
    associatedDeities: ['shiva', 'vishnu'],
    image: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d',
    icon: '💧',
    pricing: { basic: 1100, standard: 2100, premium: 4500 },
    duration: { basic: 30, standard: 45, premium: 60 },
    includes: ['Pind Daan rituals', 'Pitru Tarpan chants', 'Mantra releases'],
    requirements: ['Black sesame', 'Kusha grass', 'Barley flour'],
    samagri: ['Ganga water', 'Copper plate', 'White threads'],
    benefits: ['Gains ancestral blessings', 'Clears Pitru Dosha', 'Brings mental peace'],
    isPopular: false,
    isTrending: false,
    isActive: true,
    order: 6,
  },
];

