export const RITUALS = [
  {
    id: 'satyanarayan-puja', name: 'Satyanarayan Puja', nameHi: 'सत्यनारायण पूजा', nameBn: 'সত্যানারায়ণ পূজা',
    category: 'puja', deity: 'vishnu', price: { basic: 1100, standard: 2100, premium: 5100 },
    duration: { basic: 60, standard: 120, premium: 180 },
    description: 'A sacred ritual to invoke Lord Vishnu for prosperity and peace.',
    icon: '📿', image: '', benefits: ['Prosperity', 'Peace', 'Harmony'],
  },
  {
    id: 'rudrabhishek', name: 'Rudrabhishek', nameHi: 'रुद्राभिषेक', nameBn: 'রুদ্রাভিষেক',
    category: 'puja', deity: 'shiva', price: { basic: 1500, standard: 3100, premium: 7100 },
    duration: { basic: 60, standard: 120, premium: 240 },
    description: 'Powerful Shiva ritual for removing obstacles and negative energies.',
    icon: '🔱', image: '', benefits: ['Protection', 'Health', 'Success'],
  },
  {
    id: 'lakshmi-puja', name: 'Lakshmi Puja', nameHi: 'लक्ष्मी पूजा', nameBn: 'লক্ষ্মী পূজা',
    category: 'puja', deity: 'lakshmi', price: { basic: 1100, standard: 2100, premium: 5100 },
    duration: { basic: 45, standard: 90, premium: 150 },
    description: 'Invoke Goddess Lakshmi for wealth, abundance, and prosperity.',
    icon: '🌺', image: '', benefits: ['Wealth', 'Abundance', 'Fortune'],
  },
  {
    id: 'navgraha-puja', name: 'Navgraha Puja', nameHi: 'नवग्रह पूजा', nameBn: 'নবগ্রহ পূজা',
    category: 'puja', deity: 'shiva', price: { basic: 2100, standard: 5100, premium: 11000 },
    duration: { basic: 90, standard: 180, premium: 300 },
    description: 'Appease all nine planets for cosmic balance and removing doshas.',
    icon: '🌍', image: '', benefits: ['Planetary Peace', 'Remedy Doshas', 'Success'],
  },
  {
    id: 'griha-pravesh', name: 'Griha Pravesh', nameHi: 'गृह प्रवेश', nameBn: 'গৃহ প্রবেশ',
    category: 'sanskar', deity: 'ganesh', price: { basic: 3100, standard: 5100, premium: 11000 },
    duration: { basic: 60, standard: 120, premium: 180 },
    description: 'Vastu-shanti puja for blessing a new home with positive energy.',
    icon: '🏠', image: '', benefits: ['Vastu Peace', 'Prosperity', 'Protection'],
  },
  {
    id: 'naamkaran', name: 'Naamkaran', nameHi: 'नामकरण', nameBn: 'নামকরণ',
    category: 'sanskar', deity: 'ganesh', price: { basic: 1100, standard: 2100, premium: 3100 },
    duration: { basic: 45, standard: 90, premium: 120 },
    description: 'Sacred naming ceremony for newborns as per Vedic traditions.',
    icon: '👶', image: '', benefits: ['Blessings', 'Long Life', 'Prosperity'],
  },
  {
    id: 'birthday-puja', name: 'Birthday Puja', nameHi: 'जन्मदिन पूजा', nameBn: 'জন্মদিন পূজা',
    category: 'puja', deity: 'krishna', price: { basic: 1100, standard: 2100, premium: 5100 },
    duration: { basic: 45, standard: 90, premium: 150 },
    description: 'Birthday blessing ceremony for long life and divine protection.',
    icon: '🎂', image: '', benefits: ['Long Life', 'Protection', 'Success'],
  },
  {
    id: 'pitru-tarpan', name: 'Pitru Tarpan', nameHi: 'पितृ तर्पण', nameBn: 'পিতৃ তর্পণ',
    category: 'tarpan', deity: 'vishnu', price: { basic: 1100, standard: 2100, premium: 3100 },
    duration: { basic: 30, standard: 60, premium: 90 },
    description: 'Offerings to ancestors for peace of departed souls and family blessings.',
    icon: '🪔', image: '', benefits: ['Ancestral Peace', 'Family Blessings', 'Remedy Pitru Dosha'],
  },
  {
    id: 'daily-aarti', name: 'Daily Aarti', nameHi: 'दैनिक आरती', nameBn: 'দৈনিক আরতি',
    category: 'daily', deity: 'all', price: { basic: 500, standard: 1100, premium: 2100 },
    duration: { basic: 15, standard: 30, premium: 45 },
    description: 'Book daily aarti at your favorite temple with live streaming.',
    icon: '🪔', image: '', benefits: ['Daily Blessings', 'Positivity', 'Divine Connection'],
  },
  {
    id: 'durga-saptashati', name: 'Durga Saptashati Path', nameHi: 'दुर्गा सप्तशती पाठ', nameBn: 'দুর্গা সপ্তশতী পাঠ',
    category: 'puja', deity: 'durga', price: { basic: 2100, standard: 5100, premium: 11000 },
    duration: { basic: 180, standard: 300, premium: 480 },
    description: 'Recitation of 700 verses dedicated to Goddess Durga for protection.',
    icon: '🦁', image: '', benefits: ['Protection', 'Strength', 'Victory'],
  },
  {
    id: 'hanuman-chalisa', name: 'Hanuman Chalisa Path', nameHi: 'हनुमान चालीसा पाठ', nameBn: 'হনুমান চালিশা পাঠ',
    category: 'puja', deity: 'hanuman', price: { basic: 500, standard: 1100, premium: 2100 },
    duration: { basic: 30, standard: 60, premium: 120 },
    description: 'Sacred recitation of Hanuman Chalisa for strength and protection.',
    icon: '🙏', image: '', benefits: ['Strength', 'Protection', 'Courage'],
  },
  {
    id: 'maha-mrityunjaya', name: 'Maha Mrityunjaya Jaap', nameHi: 'महामृत्युंजय जाप', nameBn: 'মহামৃত্যুঞ্জয় জাপ',
    category: 'puja', deity: 'shiva', price: { basic: 1500, standard: 3100, premium: 7100 },
    duration: { basic: 60, standard: 120, premium: 240 },
    description: 'Powerful mantra jaap for health, healing, and longevity.',
    icon: '🕉️', image: '', benefits: ['Health', 'Healing', 'Long Life'],
  },
];

export const PUJA_CATEGORIES = [
  { id: 'puja', label: 'Pujas', labelHi: 'पूजा', labelBn: 'পূজা' },
  { id: 'sanskar', label: 'Sanskar', labelHi: 'संस्कार', labelBn: 'সংস্কার' },
  { id: 'hawan', label: 'Hawan', labelHi: 'हवन', labelBn: 'হবন' },
  { id: 'tarpan', label: 'Tarpan', labelHi: 'तर्पण', labelBn: 'তর্পণ' },
  { id: 'daily', label: 'Daily', labelHi: 'दैनिक', labelBn: 'দৈনিক' },
];
